# Generated by Django 6.1 on 2026-08-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
