# Generated by Django 6.0.6 on 2026-07-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produkt',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
